name: Dev.Opera
url: dev.opera
markdown: redcarpet
permalink: /:title
# TODO: permalink: /:categories/:title
rss_name: feed
rss_post_limit: 25
authors:
  andreasbovens:
    display_name: Andreas Bovens
    twitter: andreasbovens
  chrismills:
    display_name: Chris Mills
    twitter: chrisdavidmills
  shwetankdixit:
    display_name: Shwetank Dixit
    twitter: shwetank
  pepelsbey:
    display_name: Vadim Makeev
    twitter: pepelsbey
