title: Dev.Opera
url: https://dev.opera.com/
permalink: /:categories/:title/
future: true

markdown: kramdown
kramdown:
  auto_ids: true
  transliterated_header_ids: true

include:
- '.htaccess'
exclude:
- 'node_modules'
- 'package.json'
- 'bower_components'
- 'bower.json'
- 'Gruntfile.js'
- 'install.sh'
- 'README.md'
- 'LICENSE.md'
- 'CONTRIBUTING.md'
- '*.scss'

collections:
  authors:
    output: true
    permalink: /authors/:path/

defaults:
- scope:
    path: 'articles'
    type: 'posts'
  values:
    category: 'articles'
    layout: 'entry'
    language: 'en'
- scope:
    path: 'blog'
    type: 'posts'
  values:
    category: 'blog'
    layout: 'entry'
    language: 'en'
- scope:
    path: 'tv'
    type: 'posts'
  values:
    category: 'tv'
    layout: 'entry'
    language: 'en'
- scope:
    path: ''
    type: 'authors'
  values:
    layout: 'author'
