title: Dev.Opera
url: http://dev.opera.com/
permalink: /:categories/:title/
future: false

markdown: kramdown
kramdown:
  auto_ids: true
  transliterated_header_ids: true

include:
- '.htaccess'
exclude:
- 'node_modules'
- 'Gruntfile.js'
- 'package.json'
- 'install.sh'
- 'README.md'
- 'LICENSE.md'
- 'CONTRIBUTING.md'
- '*.scss'
