title: Dev.Opera
markdown: kramdown
kramdown:
  auto_ids: true
  transliterated_header_ids: true
permalink: /:categories/:title/
include:
- '.htaccess'
exclude:
- 'node_modules'
- 'Gruntfile.js'
- 'package.json'
- 'README.md'
- 'LICENSE.md'
- 'styles/*.scss'
